stages:
  - build_test_quality
  - deploy

image: docker:stable
services:
    - docker:dind

build_test_quality:
  stage: build_test_quality
  script:
    - docker build -f docker/Dockerfile --target dev -t php-backend-dev .
    - docker run --rm php-backend-dev phpunit tests
    - docker run --rm php-backend-dev phpstan analyse src --level=max
    - docker run --rm php-backend-dev psalm
    - docker run --rm php-backend-dev phpmd src text cleancode,codesize,controversial,design,naming,unusedcode
    - docker run --rm php-backend-dev phpcs --standard=PSR12 src

deploy:
  stage: deploy
  script:
    - docker build -f docker/Dockerfile --target prod -t php-backend-prod .
    - docker tag php-backend-prod registry.gitlab.com/tonuser/tech-tests-portfolio:latest
    - docker push registry.gitlab.com/tonuser/tech-tests-portfolio:latest
  only:
    - main
